<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.5">
  <POU Name="PROG" Id="{971c9f67-c7aa-4c3b-a151-6b6f987c9db5}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PROG //Place to program application specific code
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PROG">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>