<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="tcUNIT_APP_RUN" Id="{677fcae4-9d84-425e-8fcd-8e3d3a1985e8}" SpecialFunc="None">
    <Declaration><![CDATA[(* tcUNIT Tests: Add this program to PLC task in order to run tcUNIT tests against the declared POU test suites. 
   see https://tcunit.org/ for documentation. *)
PROGRAM tcUNIT_APP_RUN

VAR
    (* Declare standard library POU tests to be run
       E.g. fbMoveNonLinearSlits: FB_MoveNonLinearSlits_Test; *)
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
    <LineIds Name="tcUNIT_APP_RUN">
      <LineId Id="45" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>