<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="tcUNIT_APP_RUN" Id="{1cbcbdc6-2eff-474d-81ad-52783ff4b2a4}" SpecialFunc="None">
    <Declaration><![CDATA[// tcUNIT: Add this program to PLC tasks in order to run tcUNIT tests against the declared POU test suites below
PROGRAM tcUNIT_APP_RUN
VAR
    // Declare application POU tests to be run
    // e.g. fbNonLinearSlitMove: FB_NonLinearSlitMove_Test
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();
]]></ST>
    </Implementation>
    <LineIds Name="tcUNIT_APP_RUN">
      <LineId Id="45" Count="0" />
      <LineId Id="43" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>